# Dados gerais
spring.application.name=backend

# Conexão MySQL PRIVADA do Railway (sem custo de tráfego)
spring.datasource.url=jdbc:mysql://thomas.proxy.rwy.net:47919/railway?useSSL=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=IWpcdhQMzSvUWnIUQImXKSfOcVUYjEmB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 🚀 CONFIGURAÇÃO CORRETA PARA HIBERNATE 6
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Comportamento do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Outras configurações
server.port=${PORT:8080}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

livraria.upload.dir=/tmp/uploads/